language: c
compiler:
  - clang
  - gcc
script: ./autogen.sh && ./configure && make distcheck
matrix:
  include:
  - os: linux
    dist: precise
  - os: linux
    dist: trusty
addons:
  apt:
    packages:
    - libwings-dev
