title: wmforecast
email: dtorrance@piedmont.edu
description: Weather dockapp for Window Maker using the Yahoo Weather API
url: "https://wmforecast.friedcheese.org"
github_username:  d-torrance
markdown: kramdown
theme: minima
